package com.example.mobdev_lab3.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mobdev_lab3.database.entity.FileMetadata;
import com.example.mobdev_lab3.database.entity.FileMetadataTag;
import com.example.mobdev_lab3.database.entity.Tag;

import com.example.mobdev_lab3.database.dao.FileMetadataDao;
import com.example.mobdev_lab3.database.dao.FileMetadataTagDao;
import com.example.mobdev_lab3.database.dao.TagDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileMetadataDaoConfig;
    private final DaoConfig fileMetadataTagDaoConfig;
    private final DaoConfig tagDaoConfig;

    private final FileMetadataDao fileMetadataDao;
    private final FileMetadataTagDao fileMetadataTagDao;
    private final TagDao tagDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileMetadataDaoConfig = daoConfigMap.get(FileMetadataDao.class).clone();
        fileMetadataDaoConfig.initIdentityScope(type);

        fileMetadataTagDaoConfig = daoConfigMap.get(FileMetadataTagDao.class).clone();
        fileMetadataTagDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        fileMetadataDao = new FileMetadataDao(fileMetadataDaoConfig, this);
        fileMetadataTagDao = new FileMetadataTagDao(fileMetadataTagDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);

        registerDao(FileMetadata.class, fileMetadataDao);
        registerDao(FileMetadataTag.class, fileMetadataTagDao);
        registerDao(Tag.class, tagDao);
    }
    
    public void clear() {
        fileMetadataDaoConfig.clearIdentityScope();
        fileMetadataTagDaoConfig.clearIdentityScope();
        tagDaoConfig.clearIdentityScope();
    }

    public FileMetadataDao getFileMetadataDao() {
        return fileMetadataDao;
    }

    public FileMetadataTagDao getFileMetadataTagDao() {
        return fileMetadataTagDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

}
