package com.example.mobdev_lab3.database.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.example.mobdev_lab3.database.entity.FileMetadataTag;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILE_METADATA_TAG".
*/
public class FileMetadataTagDao extends AbstractDao<FileMetadataTag, Long> {

    public static final String TABLENAME = "FILE_METADATA_TAG";

    /**
     * Properties of entity FileMetadataTag.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FileMetadataId = new Property(1, Long.class, "fileMetadataId", false, "FILE_METADATA_ID");
        public final static Property TagId = new Property(2, Long.class, "tagId", false, "TAG_ID");
    }

    private DaoSession daoSession;

    private Query<FileMetadataTag> fileMetadata_FileMetadataTagsQuery;
    private Query<FileMetadataTag> tag_FileMetadataTagsQuery;

    public FileMetadataTagDao(DaoConfig config) {
        super(config);
    }
    
    public FileMetadataTagDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILE_METADATA_TAG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILE_METADATA_ID\" INTEGER NOT NULL ," + // 1: fileMetadataId
                "\"TAG_ID\" INTEGER NOT NULL );"); // 2: tagId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILE_METADATA_TAG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FileMetadataTag entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFileMetadataId());
        stmt.bindLong(3, entity.getTagId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FileMetadataTag entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFileMetadataId());
        stmt.bindLong(3, entity.getTagId());
    }

    @Override
    protected final void attachEntity(FileMetadataTag entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FileMetadataTag readEntity(Cursor cursor, int offset) {
        FileMetadataTag entity = new FileMetadataTag( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // fileMetadataId
            cursor.getLong(offset + 2) // tagId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FileMetadataTag entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFileMetadataId(cursor.getLong(offset + 1));
        entity.setTagId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FileMetadataTag entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FileMetadataTag entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FileMetadataTag entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "fileMetadataTags" to-many relationship of FileMetadata. */
    public List<FileMetadataTag> _queryFileMetadata_FileMetadataTags(Long fileMetadataId) {
        synchronized (this) {
            if (fileMetadata_FileMetadataTagsQuery == null) {
                QueryBuilder<FileMetadataTag> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FileMetadataId.eq(null));
                fileMetadata_FileMetadataTagsQuery = queryBuilder.build();
            }
        }
        Query<FileMetadataTag> query = fileMetadata_FileMetadataTagsQuery.forCurrentThread();
        query.setParameter(0, fileMetadataId);
        return query.list();
    }

    /** Internal query to resolve the "fileMetadataTags" to-many relationship of Tag. */
    public List<FileMetadataTag> _queryTag_FileMetadataTags(Long tagId) {
        synchronized (this) {
            if (tag_FileMetadataTagsQuery == null) {
                QueryBuilder<FileMetadataTag> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TagId.eq(null));
                tag_FileMetadataTagsQuery = queryBuilder.build();
            }
        }
        Query<FileMetadataTag> query = tag_FileMetadataTagsQuery.forCurrentThread();
        query.setParameter(0, tagId);
        return query.list();
    }

}
