package com.example.mobdev_lab3.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.mobdev_lab3.database.entity.FileMetadata;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILE_METADATA".
*/
public class FileMetadataDao extends AbstractDao<FileMetadata, Long> {

    public static final String TABLENAME = "FILE_METADATA";

    /**
     * Properties of entity FileMetadata.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FilePath = new Property(1, String.class, "filePath", false, "FILE_PATH");
        public final static Property FileName = new Property(2, String.class, "fileName", false, "FILE_NAME");
        public final static Property LastAccessDate = new Property(3, Long.class, "lastAccessDate", false, "LAST_ACCESS_DATE");
        public final static Property IsFavorite = new Property(4, Boolean.class, "isFavorite", false, "IS_FAVORITE");
    }

    private DaoSession daoSession;


    public FileMetadataDao(DaoConfig config) {
        super(config);
    }
    
    public FileMetadataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILE_METADATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILE_PATH\" TEXT NOT NULL ," + // 1: filePath
                "\"FILE_NAME\" TEXT NOT NULL ," + // 2: fileName
                "\"LAST_ACCESS_DATE\" INTEGER," + // 3: lastAccessDate
                "\"IS_FAVORITE\" INTEGER);"); // 4: isFavorite
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_FILE_METADATA_FILE_PATH ON \"FILE_METADATA\"" +
                " (\"FILE_PATH\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILE_METADATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FileMetadata entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFilePath());
        stmt.bindString(3, entity.getFileName());
 
        Long lastAccessDate = entity.getLastAccessDate();
        if (lastAccessDate != null) {
            stmt.bindLong(4, lastAccessDate);
        }
 
        Boolean isFavorite = entity.getIsFavorite();
        if (isFavorite != null) {
            stmt.bindLong(5, isFavorite ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FileMetadata entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFilePath());
        stmt.bindString(3, entity.getFileName());
 
        Long lastAccessDate = entity.getLastAccessDate();
        if (lastAccessDate != null) {
            stmt.bindLong(4, lastAccessDate);
        }
 
        Boolean isFavorite = entity.getIsFavorite();
        if (isFavorite != null) {
            stmt.bindLong(5, isFavorite ? 1L: 0L);
        }
    }

    @Override
    protected final void attachEntity(FileMetadata entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FileMetadata readEntity(Cursor cursor, int offset) {
        FileMetadata entity = new FileMetadata( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // filePath
            cursor.getString(offset + 2), // fileName
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // lastAccessDate
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0 // isFavorite
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FileMetadata entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFilePath(cursor.getString(offset + 1));
        entity.setFileName(cursor.getString(offset + 2));
        entity.setLastAccessDate(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIsFavorite(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FileMetadata entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FileMetadata entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FileMetadata entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
